/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MedicalVisitsRouteImport } from './routes/medical-visits'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CacesRouteImport } from './routes/caces'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsReferenceDataRouteImport } from './routes/settings/reference-data'
import { Route as SettingsBackupRouteImport } from './routes/settings/backup'
import { Route as SettingsAlertsRouteImport } from './routes/settings/alerts'
import { Route as EmployeesIdRouteImport } from './routes/employees_.$id'

const MedicalVisitsRoute = MedicalVisitsRouteImport.update({
  id: '/medical-visits',
  path: '/medical-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CacesRoute = CacesRouteImport.update({
  id: '/caces',
  path: '/caces',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsReferenceDataRoute = SettingsReferenceDataRouteImport.update({
  id: '/settings/reference-data',
  path: '/settings/reference-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/settings/backup',
  path: '/settings/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAlertsRoute = SettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/employees_/$id',
  path: '/employees/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/caces': typeof CacesRoute
  '/contracts': typeof ContractsRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/home': typeof HomeRoute
  '/medical-visits': typeof MedicalVisitsRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/reference-data': typeof SettingsReferenceDataRoute
  '/settings/system': typeof SettingsSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/caces': typeof CacesRoute
  '/contracts': typeof ContractsRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/home': typeof HomeRoute
  '/medical-visits': typeof MedicalVisitsRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/reference-data': typeof SettingsReferenceDataRoute
  '/settings/system': typeof SettingsSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/caces': typeof CacesRoute
  '/contracts': typeof ContractsRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/home': typeof HomeRoute
  '/medical-visits': typeof MedicalVisitsRoute
  '/employees_/$id': typeof EmployeesIdRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/reference-data': typeof SettingsReferenceDataRoute
  '/settings/system': typeof SettingsSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/caces'
    | '/contracts'
    | '/documents'
    | '/employees'
    | '/home'
    | '/medical-visits'
    | '/employees/$id'
    | '/settings/alerts'
    | '/settings/backup'
    | '/settings/reference-data'
    | '/settings/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/caces'
    | '/contracts'
    | '/documents'
    | '/employees'
    | '/home'
    | '/medical-visits'
    | '/employees/$id'
    | '/settings/alerts'
    | '/settings/backup'
    | '/settings/reference-data'
    | '/settings/system'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/caces'
    | '/contracts'
    | '/documents'
    | '/employees'
    | '/home'
    | '/medical-visits'
    | '/employees_/$id'
    | '/settings/alerts'
    | '/settings/backup'
    | '/settings/reference-data'
    | '/settings/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CacesRoute: typeof CacesRoute
  ContractsRoute: typeof ContractsRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployeesRoute: typeof EmployeesRoute
  HomeRoute: typeof HomeRoute
  MedicalVisitsRoute: typeof MedicalVisitsRoute
  EmployeesIdRoute: typeof EmployeesIdRoute
  SettingsAlertsRoute: typeof SettingsAlertsRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsReferenceDataRoute: typeof SettingsReferenceDataRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/medical-visits': {
      id: '/medical-visits'
      path: '/medical-visits'
      fullPath: '/medical-visits'
      preLoaderRoute: typeof MedicalVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caces': {
      id: '/caces'
      path: '/caces'
      fullPath: '/caces'
      preLoaderRoute: typeof CacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/reference-data': {
      id: '/settings/reference-data'
      path: '/settings/reference-data'
      fullPath: '/settings/reference-data'
      preLoaderRoute: typeof SettingsReferenceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/alerts': {
      id: '/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof SettingsAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees_/$id': {
      id: '/employees_/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CacesRoute: CacesRoute,
  ContractsRoute: ContractsRoute,
  DocumentsRoute: DocumentsRoute,
  EmployeesRoute: EmployeesRoute,
  HomeRoute: HomeRoute,
  MedicalVisitsRoute: MedicalVisitsRoute,
  EmployeesIdRoute: EmployeesIdRoute,
  SettingsAlertsRoute: SettingsAlertsRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsReferenceDataRoute: SettingsReferenceDataRoute,
  SettingsSystemRoute: SettingsSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
